<!DOCTYPE html>
<html>
<head>
    <title>Trip Report</title>
    <style>
        body {
            font-family: Arial, sans-serif;
        }
        table {
            width: 100%;
            border-collapse: collapse;
            margin-bottom: 20px;
        }
        table, th, td {
            border: 1px solid black;
        }
        th, td {
            padding: 8px;
            text-align: left;
        }
        th {
            background-color: #f2f2f2;
        }
        .summary-table {
            margin-bottom: 40px;
        }
        .footer {
            position: fixed;
            bottom: 0;
            left: 0;
            width: 100%;
            text-align: center;
            font-size: 12px;
        }
    </style>
</head>
<body>
    <h1>Report</h1>
    <p>Generated On: {{ $generatedOn }}</p>
    
    <h2>General</h2>
    <table class="summary-table">
        <tr>
            <th>Earning (Monthly)</th>
            <td>{{ $earningMonthly }} MAD</td>
        </tr>
        <tr>
            <th>Earning(Annual)</th>
            <td>{{ $earningAnnual }} MAD</td>
        </tr>
        <tr>
            <th>Bookings (Monthly)</th>
            <td>{{ $bookingsMonthly }} Bookings</td>
        </tr>
        <tr>
            <th>Pending Payments</th>
            <td>{{ $pendingPayments }} Payments</td>
        </tr>
        <tr>
            <th>New Users (Monthly)</th>
            <td>{{ $newUsers }} Users</td>
        </tr>
    </table>

    <h2>Top Five Destinations</h2>
    @foreach($topDestinations as $destination)
        <h3>{{ $destination->destination }}</h3>
        <p>Bookings Count: {{ $destination->bookings_count }}</p>
        <hr>
    @endforeach

    <h2>Bookings Status (Monthly)</h2>
    @foreach($bookingStatuses as $status)
        <h3>{{ $status->status }}</h3>
        <p>Status Count: {{ $status->status_count }}</p>
        <hr>
    @endforeach

    <div class="footer">
        <p>Generated by Explore Morocco</p>
    </div>
</body>
</html>
